import Avatar1 from "../../assets/images/Ellipse 32.png";
import Avatar2 from "../../assets/images/Ellipse 38.png";
import Avatar3 from "../../assets/images/Ellipse 44.png";
import Avatar4 from "../../assets/images/Ellipse 50.png";
import Avatar5 from "../../assets/images/Ellipse 56.png";
import Avatar6 from "../../assets/images/Ellipse1.png";
import Avatar7 from "../../assets/images/Ellipse2.png";
import Avatar8 from "../../assets/images/Ellipse3.png";
import Avatar9 from "../../assets/images/Ellipse4.png";
import Avatar10 from "../../assets/images/Ellipse5.png";
import Avatar12 from "../../assets/images/Ellipse6.png";
import Avatar13 from "../../assets/images/Ellipse7.png";
import Avatar14 from "../../assets/images/Ellipse8.png";
import Avatar15 from "../../assets/images/Ellipse9.png";
import Avatar16 from "../../assets/images/Ellipse10.png";
import Avatar17 from "../../assets/images/Ellipse11.png";
import Avatar18 from "../../assets/images/Ellipse12.png";
import Avatar19 from "../../assets/images/Ellipse13.png";
import Avatar20 from "../../assets/images/Ellipse14.png";
import Avatar21 from "../../assets/images/Ellipse 39.png";
import Avatar22 from "../../assets/images/Ellipse 45.png";
import Avatar23 from "../../assets/images/Ellipse 57.png";

import Medallion1 from "../../assets/images/Medallions/Medallion1.png";
import Medallion2 from "../../assets/images/Medallions/Medallion2.png";
import Medallion4 from "../../assets/images/Medallions/Medallion4.png";
import Medallion5 from "../../assets/images/Medallions/Medallion5.png";
import Medallion6 from "../../assets/images/Medallions/Medallion6.png";
import Medallion7 from "../../assets/images/Medallions/Medallion7.png";
import Medallion8 from "../../assets/images/Medallions/Medallion8.png";
import Ribbon1 from "../../assets/images/Ribbons/Ribbon1.png";
import Ribbon2 from "../../assets/images/Ribbons/Ribbon2.png";
import Ribbon4 from "../../assets/images/Ribbons/Ribbon4.png";
import Ribbon5 from "../../assets/images/Ribbons/Ribbon5.png";
import Ribbon6 from "../../assets/images/Ribbons/Ribbon6.png";
import Ribbon7 from "../../assets/images/Ribbons/Ribbon7.png";
import Ribbon8 from "../../assets/images/Ribbons/Ribbon8.png";

export const details = [
  {
    rank: 1,
    user: "Barry Focha",
    community: "Pudgy Penguins",
    twitter: "@bfocha_1",
    status: true,
    img: Avatar1,
    star: [
      { name: "Medallion6", star: Medallion6 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon8", star: Ribbon8 },
      { name: "Ribbon1", star: Ribbon1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 725324908,
  },
  {
    rank: 2,
    user: "Nick Francis",
    community: "Doodles",
    twitter: "@nicholas_francis",
    status: false,
    img: Avatar2,
    star: [
      { name: "Medallion2", star: Medallion2 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
      { name: "Ribbon1", star: Ribbon1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 613392812,
  },
  {
    rank: 3,
    user: "Jack Rosenthal",
    community: "Genuine Undead",
    twitter: "@landao_cal",
    status: true,
    img: Avatar3,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
      { name: "Ribbon1", star: Ribbon1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 605122133,
  },
  {
    rank: 4,
    user: "Andrew Epprecht",
    status: true,
    community: "Genuine Undead",
    twitter: "@cryptobreaky",
    img: Avatar4,
    star: [
      { name: "Medallion8", star: Medallion8 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon2", star: Ribbon2 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 587273884,
  },
  {
    rank: 5,
    user: "Kyle Fay",
    community: "DeGods",
    twitter: "@cryptocowboy_1",
    status: true,
    img: Avatar5,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon6", star: Ribbon6 },
      { name: "Ribbon7", star: Ribbon7 },
    ],
    xp: 566332784,
  },
  {
    rank: 6,
    user: "Miles Boxer",
    community: "Doodles",
    twitter: "@miles_boxer",
    status: null,
    img: Avatar1,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 525880032,
  },
  {
    rank: 7,
    user: "Alec James",
    community: "Doodles",
    twitter: "@wajjey",
    status: false,
    img: Avatar2,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon4", star: Ribbon4 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 508949676,
  },
  {
    rank: 8,
    user: "Nick Dahlborg",
    community: "DeGods",
    twitter: "@landao_cal",
    status: true,
    img: Avatar4,
    star: [
      { name: "Medallion4", star: Medallion4 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 460880247,
  },
  {
    rank: 9,
    user: "Dan Hepworth",
    community: "Genuine Undead",
    twitter: "@danhepworth",
    status: true,
    img: Avatar5,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 452508671,
  },
  {
    rank: 10,
    user: "Joe Zakielarz",
    community: "DeGods",
    twitter: "@joe_zak",
    status: false,
    img: Avatar1,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon5", star: Ribbon5 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 421155760,
  },
  {
    rank: 11,
    user: "Weston Willingham",
    community: "Pudgy Penguins",
    twitter: "@west_willing",
    status: true,
    img: Avatar2,
    star: [
      { name: "Medallion6", star: Medallion6 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 401320165,
  },
  {
    rank: 12,
    user: "Taher Khambati",
    community: "Doodles",
    twitter: "@tah_khambati",
    status: null,
    img: Avatar3,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 329584062,
  },
  {
    rank: 13,
    user: "William Hayward",
    community: "Genuine Undead",
    twitter: "@willhayward",
    status: null,
    img: Avatar4,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 307945592,
  },
  {
    rank: 14,
    user: "Yesh Shah",
    community: "Genuine Undead",
    twitter: "@shahman",
    status: true,
    img: Avatar5,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 287568756,
  },
  {
    rank: 15,
    user: "Barry Focha",
    community: "DeGods",
    twitter: "@bfocha_1",
    status: true,
    img: Avatar1,
    star: [
      { name: "Medallion6", star: Medallion6 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon8", star: Ribbon8 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 16,
    user: "Nick Francis",
    community: "Pudgy Penguins",
    twitter: "@alley_daviv",
    status: false,
    img: Avatar2,
    star: [
      { name: "Medallion2", star: Medallion2 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 17,
    user: "Jack Rosenthal",
    community: "Doodles",
    twitter: "@gon_mass",
    status: true,
    img: Avatar3,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 18,
    user: "Andrew Epprecht",
    community: "Doodles",
    twitter: "@bradaon_1",
    status: true,
    img: Avatar4,
    star: [
      { name: "Medallion8", star: Medallion8 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon2", star: Ribbon2 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 19,
    user: "Kyle Fay",
    community: "Genuine Undead",
    twitter: "@jan_cena",
    status: false,
    img: Avatar5,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon6", star: Ribbon6 },
      { name: "Ribbon7", star: Ribbon7 },
    ],
    xp: 567847576,
  },
  {
    rank: 20,
    user: "Barry Focha",
    twitter: "@boxo_fix",
    community: "DeGods",
    status: true,
    img: Avatar1,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 21,
    user: "Nick Francis",
    twitter: "@david_velli",
    community: "Pudgy Penguins",
    status: false,
    img: Avatar2,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon4", star: Ribbon4 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 22,
    user: "Jack Rosenthal",
    twitter: "@kisma_majo_7",
    community: "Doodles",
    status: true,
    img: Avatar3,
    star: [
      { name: "Medallion4", star: Medallion4 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 23,
    user: "Jack Rosenthal",
    community: "Pudgy Penguins",
    twitter: "@blueray_2",
    status: true,
    img: Avatar3,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 24,
    user: "Andrew Epprecht",
    community: "Genuine Undead",
    twitter: "@washi_masco",
    status: true,
    img: Avatar4,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon5", star: Ribbon5 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 25,
    user: "Kyle Fay",
    community: "DeGods",
    twitter: "@pdjack",
    status: false,
    img: Avatar5,
    star: [
      { name: "Medallion6", star: Medallion6 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 26,
    user: "Barry Focha",
    community: "Pudgy Penguins",
    twitter: "@alley_david",
    status: true,
    img: Avatar1,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 27,
    user: "Nick Francis",
    community: "Doodles",
    twitter: "@bruth",
    status: false,
    img: Avatar2,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 28,
    user: "Jack Rosenthal",
    community: "Doodles",
    twitter: "@glidan_boy",
    status: true,
    img: Avatar3,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 29,
    user: "Andrew Epprecht",
    community: "Genuine Undead",
    twitter: "@macrow",
    status: true,
    img: Avatar4,
    star: [
      { name: "Medallion6", star: Medallion6 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon8", star: Ribbon8 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 30,
    user: "Kyle Fay",
    community: "DeGods",
    twitter: "@shali_girrl",
    status: false,
    img: Avatar5,
    star: [
      { name: "Medallion2", star: Medallion2 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 31,
    user: "Barry Focha",
    community: "Pudgy Penguins",
    twitter: "@pizerod",
    status: true,
    img: Avatar1,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 32,
    user: "Nick Francis",
    twitter: "@good_boy",
    community: "Doodles",
    status: false,
    img: Avatar2,
    star: [
      { name: "Medallion8", star: Medallion8 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon2", star: Ribbon2 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 33,
    user: "Barry Focha",
    community: "Pudgy Penguins",
    twitter: "@pizerod",
    status: true,
    img: Avatar1,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon6", star: Ribbon6 },
      { name: "Ribbon7", star: Ribbon7 },
    ],
    xp: 567847576,
  },
  {
    rank: 34,
    user: "Jack Rosenthal",
    community: "Genuine Undead",
    twitter: "@dan_mass",
    status: true,
    img: Avatar3,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 35,
    user: "Andrew Epprecht",
    community: "DeGods",
    twitter: "@hari_7",
    status: true,
    img: Avatar4,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon4", star: Ribbon4 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 36,
    user: "Kyle Fay",
    community: "Pudgy Penguins",
    twitter: "@binky_boy5",
    status: false,
    img: Avatar5,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon4", star: Ribbon4 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 37,
    user: "Barry Focha",
    community: "Doodles",
    twitter: "@motto_roll",
    status: true,
    img: Avatar1,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 38,
    user: "Nick Francis",
    community: "Genuine Undead",
    twitter: "@hifi_jack",
    status: false,
    img: Avatar2,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 39,
    user: "Jack Rosenthal",
    community: "Genuine Undead",
    twitter: "@achi_jck",
    status: true,
    img: Avatar3,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 40,
    user: "Andrew Epprecht",
    community: "DeGods",
    twitter: "@gluway",
    status: true,
    img: Avatar4,
    star: [
      { name: "Medallion7", star: Medallion8 },
      { name: "Medallion3", star: Medallion1 },
      { name: "Ribbon2", star: Ribbon2 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 41,
    user: "Barry Focha",
    community: "Pudgy Penguins",
    twitter: "@gluway",
    status: true,
    img: Avatar1,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon4", star: Ribbon4 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 42,
    user: "Nick Francis",
    community: "Doodles",
    twitter: "@fixed_box",
    status: false,
    img: Avatar2,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 43,
    user: "Jack Rosenthal",
    community: "Doodles",
    twitter: "@rumasss_fgh",
    status: true,
    img: Avatar3,
    star: [
      { name: "Medallion4", star: Medallion4 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 44,
    user: "Andrew Epprecht",
    community: "Genuine Undead",
    twitter: "@hello_boy",
    status: true,
    img: Avatar4,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 45,
    user: "Kyle Fay",
    community: "Genuine Undead",
    twitter: "@tavid_billey",
    status: false,
    img: Avatar5,
    star: [
      { name: "Medallion4", star: Medallion4 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 46,
    user: "Barry Focha",
    community: "Pudgy Penguins",
    twitter: "@jack_7",
    status: true,
    img: Avatar1,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 47,
    user: "Nick Francis",
    community: "Doodles",
    twitter: "@messi_10",
    status: false,
    img: Avatar2,
    star: [
      { name: "Medallion4", star: Medallion4 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 48,
    user: "Jack Rosenthal",
    community: "Doodles",
    twitter: "@tah_mah",
    status: true,
    img: Avatar3,
    star: [
      { name: "Medallion4", star: Medallion4 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 49,
    user: "Andrew Epprecht",
    community: "Genuine Undead",
    twitter: "@willhayward",
    status: true,
    img: Avatar4,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
  {
    rank: 50,
    user: "Kyle Fay",
    community: "Genuine Undead",
    twitter: "@shahaman",
    status: false,
    img: Avatar5,
    star: [
      { name: "Medallion4", star: Medallion4 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 567847576,
  },
];

export const demoDetails = [
  {
    rank: 1,
    user: "@niftyneighbor#2802",
    id: "#2802",
    community: "Space Catz",
    twitter: "@niftyneighbor28",
    status: true,
    img: Avatar6,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion6", star: Medallion6 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon8", star: Ribbon8 },
      { name: "Ribbon1", star: Ribbon1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 725324908,
  },
  {
    rank: 2,
    user: "@slowpickle#2802",
    id: "#1450",
    community: "Valereum",
    twitter: "@slowpickle1450",
    status: false,
    img: Avatar7,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion2", star: Medallion2 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 613392812,
  },
  {
    rank: 3,
    user: "@sparklingonion#2980",
    id: "#2980",
    community: "Edo",
    twitter: "@sparklingonion1",
    status: true,
    img: Avatar8,
    communityProfile: Avatar22,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 605122133,
  },
  {
    rank: 4,
    user: "@fluffydad#2132",
    id: "#2132",
    status: true,
    community: "Edo",
    twitter: "@fluffydad2132",
    img: Avatar9,
    communityProfile: Avatar22,
    star: [
      { name: "Medallion8", star: Medallion8 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon2", star: Ribbon2 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 587273884,
  },
  {
    rank: 5,
    user: "@elfinelephant#10",
    id: "#10",
    community: "Billow",
    twitter: "@elfinelephant10",
    status: true,
    img: Avatar10,
    communityProfile: Avatar23,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon6", star: Ribbon6 },
      { name: "Ribbon7", star: Ribbon7 },
      { name: "Ribbon7", star: Ribbon7 },
    ],
    xp: 566332784,
  },
  {
    rank: 6,
    user: "@dirtydairy#345",
    id: "#345",
    community: "Valereum",
    twitter: "@dirtydairy345",
    status: null,
    img: Avatar12,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 525880032,
  },
  {
    rank: 7,
    user: "@zestyzero#456",
    id: "#456",
    community: "Billow",
    twitter: "@zestyzero456",
    status: false,
    img: Avatar13,
    communityProfile: Avatar23,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon4", star: Ribbon4 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 508949676,
  },
  {
    rank: 8,
    user: "@acousticanxiety#445",
    id: "#445",
    community: "Space Catz",
    twitter: "@acousticanxiety",
    status: true,
    img: Avatar14,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion4", star: Medallion4 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 460880247,
  },
  {
    rank: 9,
    user: "@juicyjacket#567",
    id: "#567",
    community: "Edo",
    twitter: "@juicyjacket567",
    status: true,
    img: Avatar15,
    communityProfile: Avatar22,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 452508671,
  },
  {
    rank: 10,
    user: "@playfulgoose#709",
    id: "#709",
    community: "Valereum",
    twitter: "@playfulgoose7",
    status: false,
    img: Avatar16,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon5", star: Ribbon5 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 421155760,
  },
  {
    rank: 11,
    user: "@cuddlycattle#3366",
    id: "#3366",
    community: "Space Catz",
    twitter: "@cuddlycattle336",
    status: true,
    img: Avatar17,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion6", star: Medallion6 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 401320265,
  },
  {
    rank: 12,
    user: "@hellishhistorian#771",
    id: "#771",
    community: "Space Catz",
    twitter: "@hellishhistoria",
    status: null,
    img: Avatar18,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 329584062,
  },
  {
    rank: 13,
    user: "@pricklypotato#511",
    id: "#511",
    community: "Billow",
    twitter: "@pricklypotato51",
    status: null,
    img: Avatar19,
    communityProfile: Avatar23,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 307945592,
  },
  {
    rank: 14,
    user: "@kaputking#44",
    id: "#44",
    community: "Valereum",
    twitter: "@kaputking44",
    status: true,
    img: Avatar20,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 287568756,
  },
  {
    rank: 15,
    user: "@niftyneighbor#2802",
    id: "#2802",
    community: "Space Catz",
    twitter: "@niftyneighbor28",
    status: true,
    img: Avatar6,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion6", star: Medallion6 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon8", star: Ribbon8 },
      { name: "Ribbon1", star: Ribbon1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 725324908,
  },
  {
    rank: 16,
    user: "@slowpickle#1450",
    id: "#1450",
    community: "Valereum",
    twitter: "@slowpickle1450",
    status: false,
    img: Avatar7,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion2", star: Medallion2 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 613392812,
  },
  {
    rank: 17,
    user: "@sparklingonion#2980",
    id: "#2980",
    community: "Edo",
    twitter: "@sparklingonion1",
    status: true,
    img: Avatar8,
    communityProfile: Avatar22,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 605122133,
  },
  {
    rank: 18,
    user: "@fluffydad#2132",
    id: "#2132",
    status: true,
    community: "Edo",
    twitter: "@fluffydad2132",
    img: Avatar9,
    communityProfile: Avatar22,
    star: [
      { name: "Medallion8", star: Medallion8 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon2", star: Ribbon2 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 587273884,
  },
  {
    rank: 19,
    user: "@elfinelephant#10",
    id: "#10",
    community: "Billow",
    twitter: "@elfinelephant10",
    status: true,
    img: Avatar10,
    communityProfile: Avatar23,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon6", star: Ribbon6 },
      { name: "Ribbon7", star: Ribbon7 },
      { name: "Ribbon7", star: Ribbon7 },
    ],
    xp: 566332784,
  },
  {
    rank: 20,
    user: "@dirtydairy#345",
    id: "#345",
    community: "Valereum",
    twitter: "@dirtydairy345",
    status: null,
    img: Avatar12,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 525880032,
  },
  {
    rank: 21,
    user: "@zestyzero#456",
    id: "#456",
    community: "Billow",
    twitter: "@zestyzero456",
    status: false,
    img: Avatar13,
    communityProfile: Avatar23,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon4", star: Ribbon4 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 508949676,
  },
  {
    rank: 22,
    user: "@acousticanxiety#445",
    id: "#445",
    community: "Space Catz",
    twitter: "@acousticanxiety",
    status: true,
    img: Avatar14,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion4", star: Medallion4 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 460880247,
  },
  {
    rank: 23,
    user: "@juicyjacket#567",
    id: "#567",
    community: "Edo",
    twitter: "@juicyjacket567",
    status: true,
    img: Avatar15,
    communityProfile: Avatar22,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 452508671,
  },
  {
    rank: 24,
    user: "@playfulgoose#709",
    id: "#709",
    community: "Valereum",
    twitter: "@playfulgoose7",
    status: false,
    img: Avatar16,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon5", star: Ribbon5 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 421155760,
  },
  {
    rank: 25,
    user: "@cuddlycattle#3366",
    id: "#3366",
    community: "Space Catz",
    twitter: "@cuddlycattle336",
    status: true,
    img: Avatar17,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion6", star: Medallion6 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 401320265,
  },
  {
    rank: 26,
    user: "@hellishhistorian#771",
    id: "#771",
    community: "Space Catz",
    twitter: "@hellishhistoria",
    status: null,
    img: Avatar18,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 329584062,
  },
  {
    rank: 27,
    user: "@pricklypotato#511",
    id: "#511",
    community: "Billow",
    twitter: "@pricklypotato51",
    status: null,
    img: Avatar19,
    communityProfile: Avatar23,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 307945592,
  },
  {
    rank: 28,
    user: "@kaputking#44",
    id: "#44",
    community: "Valereum",
    twitter: "@kaputking44",
    status: true,
    img: Avatar20,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 287568756,
  },
  {
    rank: 29,
    user: "@niftyneighbor#2802",
    id: "#2802",
    community: "Space Catz",
    twitter: "@niftyneighbor28",
    status: true,
    img: Avatar6,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion6", star: Medallion6 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon8", star: Ribbon8 },
      { name: "Ribbon1", star: Ribbon1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 725324908,
  },
  {
    rank: 30,
    user: "@slowpickle#1450",
    id: "#1450",
    community: "Valereum",
    twitter: "@slowpickle1450",
    status: false,
    img: Avatar7,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion2", star: Medallion2 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 613392812,
  },
  {
    rank: 31,
    user: "@sparklingonion#2980",
    id: "#2980",
    community: "Edo",
    twitter: "@sparklingonion1",
    status: true,
    img: Avatar8,
    communityProfile: Avatar22,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 605122133,
  },
  {
    rank: 32,
    user: "@fluffydad#2132",
    id: "#2132",
    status: true,
    community: "Edo",
    twitter: "@fluffydad2132",
    img: Avatar9,
    communityProfile: Avatar22,
    star: [
      { name: "Medallion8", star: Medallion8 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon2", star: Ribbon2 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 587273884,
  },
  {
    rank: 33,
    user: "@elfinelephant#10",
    id: "#10",
    community: "Billow",
    twitter: "@elfinelephant10",
    status: true,
    img: Avatar10,
    communityProfile: Avatar23,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon6", star: Ribbon6 },
      { name: "Ribbon7", star: Ribbon7 },
      { name: "Ribbon7", star: Ribbon7 },
    ],
    xp: 566332784,
  },
  {
    rank: 34,
    user: "@dirtydairy#345",
    id: "#345",
    community: "Valereum",
    twitter: "@dirtydairy345",
    status: null,
    img: Avatar12,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion7", star: Medallion7 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 525880032,
  },
  {
    rank: 35,
    user: "@zestyzero#456",
    id: "#456",
    community: "Billow",
    twitter: "@zestyzero456",
    status: false,
    img: Avatar13,
    communityProfile: Avatar23,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon4", star: Ribbon4 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 508949676,
  },
  {
    rank: 36,
    user: "@acousticanxiety#445",
    id: "#445",
    community: "Space Catz",
    twitter: "@acousticanxiety",
    status: true,
    img: Avatar14,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion4", star: Medallion4 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 460880247,
  },
  {
    rank: 37,
    user: "@juicyjacket#567",
    id: "#567",
    community: "Edo",
    twitter: "@juicyjacket567",
    status: true,
    img: Avatar15,
    communityProfile: Avatar22,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 452508671,
  },
  {
    rank: 38,
    user: "@playfulgoose#709",
    id: "#709",
    community: "Valereum",
    twitter: "@playfulgoose7",
    status: false,
    img: Avatar16,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon5", star: Ribbon5 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 421155760,
  },
  {
    rank: 39,
    user: "@cuddlycattle#3366",
    id: "#3366",
    community: "Space Catz",
    twitter: "@cuddlycattle336",
    status: true,
    img: Avatar17,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion6", star: Medallion6 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 401320265,
  },
  {
    rank: 40,
    user: "@hellishhistorian#771",
    id: "#771",
    community: "Space Catz",
    twitter: "@hellishhistoria",
    status: null,
    img: Avatar18,
    communityProfile: Avatar18,
    star: [
      { name: "Medallion5", star: Medallion5 },
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 329584062,
  },
  {
    rank: 41,
    user: "@pricklypotato#511",
    id: "#511",
    community: "Billow",
    twitter: "@pricklypotato51",
    status: null,
    img: Avatar19,
    communityProfile: Avatar23,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 307945592,
  },
  {
    rank: 42,
    user: "@kaputking#44",
    id: "#44",
    community: "Valereum",
    twitter: "@kaputking44",
    status: true,
    img: Avatar20,
    communityProfile: Avatar21,
    star: [
      { name: "Medallion1", star: Medallion1 },
      { name: "Ribbon1", star: Ribbon1 },
    ],
    xp: 287568756,
  },
];
